# Generated by Django 3.0.6 on 2020-09-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCode',
            fields=[
                ('service_code', models.CharField(max_length=13, primary_key=True, serialize=False, verbose_name='ШК СК')),
                ('status', models.CharField(max_length=30, verbose_name='Статус')),
                ('org_owner', models.CharField(max_length=50, verbose_name='Подразделение-владелец')),
                ('object_type', models.CharField(max_length=30, verbose_name='Тип объекта')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес')),
                ('responsible', models.CharField(max_length=50, verbose_name='Ответственный')),
                ('name_pc', models.CharField(max_length=50, verbose_name='Наименование ПК')),
                ('level', models.CharField(max_length=50, verbose_name='Уровень обслуживания')),
                ('model', models.CharField(max_length=50, verbose_name='Производитель модель')),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
                ('sn', models.CharField(max_length=50, verbose_name='Серийный номер')),
                ('ais_tp', models.CharField(max_length=50, verbose_name='АИС ТП')),
            ],
            options={
                'verbose_name': 'ШК',
                'verbose_name_plural': 'ШК',
            },
        ),
    ]
