# Generated by Django 3.0.6 on 2020-05-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Telegram ID')),
                ('username', models.CharField(max_length=50, null=True, verbose_name='Имя пользователя Telegram')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Админ?')),
                ('is_allowed', models.BooleanField(default=False, verbose_name='Допущен?')),
            ],
            options={
                'verbose_name': 'Пользователь Телеграм',
                'verbose_name_plural': 'Пользователи Телеграм',
            },
        ),
    ]
