# Generated by Django 3.0.2 on 2020-02-03 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('approved', models.BooleanField(default=False, verbose_name='Одобрен')),
                ('time_approved', models.DateTimeField(null=True, verbose_name='Когда одобрено')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Изображение')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Порядок отображения')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('cost', models.FloatField(verbose_name='Стоимость')),
                ('count', models.PositiveIntegerField(verbose_name='Количество')),
                ('category', models.ManyToManyField(to='products.Category', verbose_name='Категория')),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Comment', verbose_name='Комментарии')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Image', verbose_name='Изображения')),
            ],
        ),
    ]
